# ----------------------------
#     Backend Build
# ----------------------------
FROM python:3.12-bookworm

RUN apt-get update && apt-get install --no-install-suggests --no-install-recommends --yes pipx

ENV PATH="/root/.local/bin:${PATH}"
ENV PYTHONPATH="${PYTHONPATH}:/app/backend"
WORKDIR /app

RUN pipx install poetry
RUN pipx inject poetry poetry-plugin-bundle

COPY ./poetry.lock ./poetry.lock
COPY ./pyproject.toml ./pyproject.toml
RUN poetry install --no-root
RUN poetry add gunicorn

COPY ./backend ./backend
CMD ["poetry", "run", "python3", "./backend/anomaly_detection/scheduler.py"]